from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

router = APIRouter()


class PromptRequest(BaseModel):
    model: str
    prompt: str


@router.post("/chat")
async def chat(request: PromptRequest):
    try:
        prompt = request.prompt
        model_name = request.model
        
        mock_response = f"[Mock Response from {model_name}]\n\nYou asked: \"{prompt}\"\n\nThis is a placeholder response. In a real implementation, this would be generated by the fine-tuned model. The model would process your prompt and generate a contextual response based on the training data."
        
        return {
            "response": mock_response,
            "model": model_name
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

